import numpy as mynp
#print(help(mynp.delete))
myarr1 = mynp.arange(10)
print("deleting element present at index 4")
myarr2 = mynp.delete(myarr1, 4)
print(myarr2)
print("deleting elements from indices 2 to 5")
myarr3 = mynp.delete(myarr1, mynp.s_[2:6])
print(myarr3)
myarr4 = mynp.arange(9).reshape(3,3)
print("Since no axis is specified. So, flattening will be done for 2-D array")
myarr5 = mynp.delete(myarr4,2)
print(myarr5)
print("axis-0 is specified. So deleting will be done for that row index")
myarr6 = mynp.delete(myarr4,1, axis=0)
print(myarr6)
print("axis-1 is specified. So deleting will be done for that column index")
myarr7 = mynp.delete(myarr4,1, axis=1)
print(myarr7)